main/urls.py
from django.urls import path
from . import views


app_name = "main"

urlpatterns = [
	
	path('', views.route, name="route"),

	]

melhorrota_soluclean/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('main.urls', namespace="main")),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main/models.py
from django.db import models

main/views.py
from django.shortcuts import render
from django.conf import settings
from .mixins import Directions

'''
Basic view for routing 
'''
def route(request):


	context = {"google_api_key": settings.GOOGLE_API_KEY}
	return render(request, 'main/route.html', context)

main/templates/main/base.html
{% load static %}


<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- visit https://fonts.google.com/specimen/Courier+Prime?preview.text_type=custom to get script-->
  <link rel="shortcut icon" href="#">
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'main.css' %}">

  <!-- This allows us to extend the head scripts in HTML docs that have special requirements-->
  {% block extend_head %}

  {% endblock %}

</head>
<body>

  <!-- This allows us to extend the nav bar in HTML docs that have special requirements-->
  {% block extend_nav %}

  {% endblock %}

  <div class="div-container">
    
    {% include 'main/partials/logo.html' %}

    {% block content %}

    {% endblock %}

  </div>

  <!--visit https://code.jquery.com/ for jquery script-->
  <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>

  <!-- This allows us to extend the foot scripts in HTML docs that have special requirements-->
  {% block extend_footer %}

  {% endblock %}
  

</body>
</html>

main/templates/main/partials/logo.html
{% load static %}
<a href="{% url 'main:route' %}">
	<div class="brand-logo">
		<img class="logo" src="{% static 'branding/soluclean_logo.png' %}" />
	</div>
</a>

main/templates/main/route.html
{% extends 'main/base.html' %}
{% load static %}


{% block extend_head %}

<script src='https://www.google.com/recaptcha/api.js?render={{recaptcha_site_key}}'></script>

{% endblock %}

{% block extend_nav %} 

<ul class="sidenav">
  <li><a class="active" href="{% url 'main:route' %}">Roteirizador</a></li>
</ul>

{% endblock %}


{% block content %}

<h3>Calculadora de Rotas</h3>

<div class="field">

    <label for="start">Endereço de Origem</label>
    <input type="text" placeholder="*Digite o endereço" id="start" name="start">

    <input type="hidden" class="geo" id="id-lat-s" value="">
    <input type="hidden" class="geo" id="id-long-s" value="">

    <label for="end">Endereço de Destino</label>
    <input type="text" placeholder="*Digite o endereço" id="end" name="end">

   <input type="hidden" class="geo" id="id-lat-e" value="">
   <input type="hidden" class="geo" id="id-long-e" value="">

</div>



<div class="container" id="dynamicInput">
    <h3>Insira aqui todas as paradas da rota:</h3>


</div>

<input type="button" class="addbutton" value="Adicionar parada" onclick="addWaypoint('dynamicInput')">
<input type="button" class="calcbutton" id="getdir" value="Melhor Rota!">

<div id="map_canvas"></div>


<div class="field">

  <table>
    <thead>
      <tr>
        <th>Dados do trajeto</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>Partida</td>
        <td>{{directions.origin}}</td>
      </tr>
      <tr>
        <td>Destino Final</td>
        <td>{{directions.destination}}</td>
      </tr>
      <tr>
        <td>Duração Total</td>
        <td>{{directions.duration}}</td>
      </tr>
      <tr>
        <td>Distância Total</td>
        <td>{{directions.distance}}</td> <!-- {{var}} serve para por uma variável no html -->
      </tr>
      <tr>
        <td>Link do Google Maps</td>
        <td id="dir-toggle">click <a href="javascript:void(0)" onclick="DirectionsToggle()">here</a></td>
      </tr>

    </tbody>
  </table>

</div>


{% endblock %}

{% block extend_footer %}


<script type="text/javascript">

    var google_api_key = "{{google_api_key|safe}}";

  </script>

  <script src="{% static 'google_places.js' %}"></script>


{% endblock %}